### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by davedaverave** [matan1905/ComfyUI-Serving-Toolkit#1]
I set up my workflow like your put my discord bot token in, but if i go to discord and type !generate "prompt" nothing happens

**Comment by davedaverave** [comment]
I'm running Comfyui on paperspace notebook

**Comment by matan1905** [comment]
Does the bot seem online? if it is, does the command_name equals generate?

anyway you can join the discord I can help better from there https://discord.com/invite/ehu2kAyGvQ
